import smtplib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

while True:
    # Check the current time
    current_time = time.localtime()
    if current_time.tm_hour == 20 and current_time.tm_min == 45:
        # Create a message
        msg = MIMEMultipart()
        msg['From'] = "frideric-2@hotmail.com"
        msg['To'] = "issacm1224@gmail.com"
        msg['Subject'] = "TESTING"

        # Add the message body
        msg.attach(MIMEText("this is testing only, testing the python script generated by chatgpt", 'plain'))

        # Send the email
        server = smtplib.SMTP('smtp-mail.outlook.com', 587)
        server.starttls()
        server.login("frideric-2@hotmail.com", "Hotmailpw001")
        server.send_message(msg)
        server.quit()

        # Break the loop
        break
    # Wait for one minute
    time.sleep(60)
