import smtplib
import schedule
import time

def send_email():
    # Set up the SMTP server
    server = smtplib.SMTP('smtp-mail.outlook.com', 587)
    server.ehlo()
    server.starttls()
    server.login('frideric-2@hotmail.com', 'Hotmailpw001')
    
    # Compose the email
    from_address = 'frideric-2@hotmail.com'
    to_address = ['wndmiao2@gmail.com','issacm1224@gmail.com','issacmiao@yahoo.com']
    subject = 'TESTING'
    body = 'this is testing only, testing the python script generated by chatgpt, ....................lalala'
    message = 'From: {}\nTo: {}\nSubject: {}\n\n{}'.format(from_address, to_address, subject, body)
    
    # Send the email
    server.sendmail(from_address, to_address, message)
    print("Email sent!")
    server.quit()

schedule.every().day.at("19:50").do(send_email)

while True:
    schedule.run_pending()
    time.sleep(1)
