import smtplib
from email.mime.text import MIMEText
from datetime import datetime, timedelta
import time

def send_email(subject, message, from_email, to_emails):
    msg = MIMEText(message)
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = ", ".join(to_emails)
    
    smtp = smtplib.SMTP('smtp.live.com', 587)
    smtp.ehlo()
    smtp.starttls()
    smtp.login(from_email, "Hotmailpw001")
    smtp.sendmail(from_email, to_emails, msg.as_string())
    smtp.quit()
    
subject = "TESTING"
message = "this is testing only, testing the python script generated by chatgpt, lalalalalala"
from_email = "frideric-2@hotmail.com"
to_emails = ["ISSACM1224@gmail.com", "wndmiao2@gmail.com", "issacmiao@yahoo.com"]

send_time = datetime.now().replace(hour=21, minute=0, second=0, microsecond=0)
if send_time < datetime.now():
    send_time = send_time + timedelta(days=1)
time.sleep((send_time-datetime.now()).total_seconds())
send_email(subject, message, from_email, to_emails)
